{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "vW2Rk0H_OhcN",
        "outputId": "6b085aed-657d-49fb-9874-ac1ae56e76d0"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting streamlit\n",
            "  Downloading streamlit-1.52.2-py3-none-any.whl.metadata (9.8 kB)\n",
            "Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)\n",
            "Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)\n",
            "Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)\n",
            "Requirement already satisfied: cachetools<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.4)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)\n",
            "Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)\n",
            "Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (25.0)\n",
            "Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)\n",
            "Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.5)\n",
            "Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)\n",
            "Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.2)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)\n",
            "Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)\n",
            "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.45)\n",
            "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
            "  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)\n",
            "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)\n",
            "Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)\n",
            "Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.5.1)\n",
            "Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)\n",
            "Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)\n",
            "Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (3.18.3)\n",
            "Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)\n",
            "Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.13.0)\n",
            "Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.25.1)\n",
            "Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.13.0)\n",
            "Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8)\n",
            "Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)\n",
            "Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2025.11.12)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.4)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
            "Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.23)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)\n",
            "Downloading streamlit-1.52.2-py3-none-any.whl (9.0 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m9.0/9.0 MB\u001b[0m \u001b[31m66.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.9/6.9 MB\u001b[0m \u001b[31m56.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: pydeck, streamlit\n",
            "Successfully installed pydeck-0.9.1 streamlit-1.52.2\n"
          ]
        }
      ],
      "source": [
        "pip install streamlit yfinance pandas\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "cpDaJ06fPXdy",
        "outputId": "9f0b56c0-1ac6-411e-8b81-a77817edb0ab"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Overwriting app.py\n"
          ]
        }
      ],
      "source": [
        "%%writefile app.py\n",
        "import streamlit as st\n",
        "import yfinance as yf\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "\n",
        "st.set_page_config(page_title=\"Financial Health Checkup\", layout=\"wide\")\n",
        "\n",
        "# -----------------------------\n",
        "# Helper\n",
        "# -----------------------------\n",
        "def safe_get(df, row):\n",
        "    try:\n",
        "        return df.loc[row]\n",
        "    except:\n",
        "        return None\n",
        "\n",
        "# -----------------------------\n",
        "# Fetch 5-year financial data\n",
        "# -----------------------------\n",
        "def fetch_financials_5y(ticker):\n",
        "    stock = yf.Ticker(ticker)\n",
        "\n",
        "    income = stock.financials\n",
        "    balance = stock.balance_sheet\n",
        "\n",
        "    if income.empty or balance.empty:\n",
        "        raise ValueError(\"Financial data not available\")\n",
        "\n",
        "    df = pd.DataFrame({\n",
        "        \"Revenue\": safe_get(income, \"Total Revenue\"),\n",
        "        \"Net Income\": safe_get(income, \"Net Income\"),\n",
        "        \"Operating Income\": safe_get(income, \"Operating Income\"),\n",
        "        \"Current Assets\": safe_get(balance, \"Current Assets\"),\n",
        "        \"Current Liabilities\": safe_get(balance, \"Current Liabilities\"),\n",
        "        \"Inventory\": safe_get(balance, \"Inventory\"),\n",
        "        \"Total Assets\": safe_get(balance, \"Total Assets\"),\n",
        "        \"Total Liabilities\": safe_get(balance, \"Total Liabilities Net Minority Interest\"),\n",
        "        \"Equity\": safe_get(balance, \"Stockholders Equity\"),\n",
        "    })\n",
        "\n",
        "    return df.dropna(how=\"all\")\n",
        "\n",
        "# -----------------------------\n",
        "# Calculate ratios\n",
        "# -----------------------------\n",
        "def calculate_ratios(df):\n",
        "    ratios = pd.DataFrame(index=df.index)\n",
        "\n",
        "    if \"Current Assets\" in df and \"Current Liabilities\" in df:\n",
        "        ratios[\"Current Ratio\"] = df[\"Current Assets\"] / df[\"Current Liabilities\"]\n",
        "        ratios[\"Quick Ratio\"] = (\n",
        "            (df[\"Current Assets\"] - df[\"Inventory\"].fillna(0))\n",
        "            / df[\"Current Liabilities\"]\n",
        "        )\n",
        "\n",
        "    if \"Net Income\" in df and \"Equity\" in df:\n",
        "        ratios[\"ROE\"] = df[\"Net Income\"] / df[\"Equity\"]\n",
        "\n",
        "    if \"Operating Income\" in df and \"Revenue\" in df:\n",
        "        ratios[\"Operating Margin\"] = df[\"Operating Income\"] / df[\"Revenue\"]\n",
        "\n",
        "    if \"Total Liabilities\" in df and \"Total Assets\" in df:\n",
        "        ratios[\"Debt to Assets\"] = df[\"Total Liabilities\"] / df[\"Total Assets\"]\n",
        "\n",
        "    if \"Total Liabilities\" in df and \"Equity\" in df:\n",
        "        ratios[\"Debt to Equity\"] = df[\"Total Liabilities\"] / df[\"Equity\"]\n",
        "\n",
        "    return ratios.round(2)\n",
        "\n",
        "# -----------------------------\n",
        "# Sense-based financial logic\n",
        "# -----------------------------\n",
        "def financial_health_logic(ratios):\n",
        "    latest = ratios.iloc[0]  # most recent year\n",
        "\n",
        "    strengths = []\n",
        "    risks = []\n",
        "\n",
        "    # ---- Profitability (PRIMARY driver) ----\n",
        "    if \"Operating Margin\" in latest and not pd.isna(latest[\"Operating Margin\"]):\n",
        "        if latest[\"Operating Margin\"] >= 0.2:\n",
        "            strengths.append(\"Strong operating profitability and pricing power\")\n",
        "        elif latest[\"Operating Margin\"] < 0.1:\n",
        "            risks.append(\"Weak operating profitability\")\n",
        "\n",
        "    if \"ROE\" in latest and not pd.isna(latest[\"ROE\"]):\n",
        "        if latest[\"ROE\"] >= 0.2:\n",
        "            strengths.append(\"High return on equity indicates efficient capital use\")\n",
        "        elif latest[\"ROE\"] < 0.1:\n",
        "            risks.append(\"Low return on equity\")\n",
        "\n",
        "    # ---- Liquidity (CONDITIONAL) ----\n",
        "    if \"Current Ratio\" in latest and not pd.isna(latest[\"Current Ratio\"]):\n",
        "        if latest[\"Current Ratio\"] < 1:\n",
        "            if \"Operating Margin\" in latest and latest[\"Operating Margin\"] >= 0.15:\n",
        "                strengths.append(\n",
        "                    \"Low balance-sheet liquidity offset by strong operating cash flows\"\n",
        "                )\n",
        "            else:\n",
        "                risks.append(\"Potential short-term liquidity pressure\")\n",
        "\n",
        "    # ---- Leverage (CONDITIONAL) ----\n",
        "    if \"Debt to Equity\" in latest and not pd.isna(latest[\"Debt to Equity\"]):\n",
        "        if latest[\"Debt to Equity\"] > 2.5:\n",
        "            if \"ROE\" in latest and latest[\"ROE\"] >= 0.15:\n",
        "                strengths.append(\n",
        "                    \"High leverage supported by strong returns on equity\"\n",
        "                )\n",
        "            else:\n",
        "                risks.append(\"High leverage with insufficient return buffer\")\n",
        "\n",
        "    # ---- Trend stability (McKinsey-style) ----\n",
        "    for col in [\"ROE\", \"Operating Margin\"]:\n",
        "        if col in ratios and ratios[col].std() > 0.12:\n",
        "            risks.append(f\"High volatility observed in {col} over time\")\n",
        "\n",
        "    # ---- Final verdict logic ----\n",
        "    if len(risks) == 0 and len(strengths) >= 3:\n",
        "        verdict = \"🟢 Strong Financial Health\"\n",
        "    elif len(risks) <= 2:\n",
        "        verdict = \"🟡 Moderate Financial Health\"\n",
        "    else:\n",
        "        verdict = \"🔴 Weak Financial Health\"\n",
        "\n",
        "    return verdict, strengths, risks\n",
        "\n",
        "# -----------------------------\n",
        "# Streamlit UI\n",
        "# -----------------------------\n",
        "st.title(\"📊 Financial Health Checker\")\n",
        "\n",
        "ticker = st.text_input(\n",
        "    \"Enter listed company ticker 🇺🇸 US Stocks (NYSE / NASDAQ)\n",
        "\n",
        "(use ticker as-is)\n",
        "\n",
        "Apple Inc. → AAPL\n",
        "\n",
        "Microsoft Corporation → MSFT\n",
        "\n",
        "Alphabet Inc. → GOOGL\n",
        "\n",
        "Amazon.com Inc. → AMZN\n",
        "\n",
        "NVIDIA Corporation → NVDA\n",
        "\n",
        "Tesla Inc. → TSLA\n",
        "\n",
        "Meta Platforms Inc. → META\n",
        "\n",
        "Johnson & Johnson → JNJ\n",
        "\n",
        "JPMorgan Chase & Co. → JPM\n",
        "\n",
        "🇮🇳 Indian Stocks (NSE)\n",
        "\n",
        "(important: add .NS)\n",
        "\n",
        "Large Caps\n",
        "\n",
        "Reliance Industries Ltd. → RELIANCE.NS\n",
        "\n",
        "Tata Consultancy Services Ltd. → TCS.NS\n",
        "\n",
        "Infosys Ltd. → INFY.NS\n",
        "\n",
        "HDFC Bank Ltd. → HDFCBANK.NS\n",
        "\n",
        "ICICI Bank Ltd. → ICICIBANK.NS\n",
        "\n",
        "Bharti Airtel Ltd. → BHARTIARTL.NS\n",
        "\n",
        "Manufacturing / Auto\n",
        "\n",
        "Tata Motors Ltd. → TATAMOTORS.NS\n",
        "\n",
        "Mahindra & Mahindra Ltd. → M&M.NS\n",
        "\n",
        "Larsen & Toubro Ltd. → LT.NS\n",
        "\n",
        "🇪🇺 Europe\n",
        "\n",
        "(use exchange suffix)\n",
        "\n",
        "Nestlé S.A. → NESN.SW\n",
        "\n",
        "SAP SE → SAP.DE\n",
        "\n",
        "Unilever PLC → ULVR.L\n",
        "\n",
        "ASML Holding N.V. → ASML.AS\n",
        "\n",
        "🏦 Banks & Financial Services (Good stress-test for your logic)\n",
        "\n",
        "Goldman Sachs Group Inc. → GS\n",
        "\n",
        "Morgan Stanley → MS\n",
        "\n",
        "State Bank of India → SBIN.NS\n",
        "\n",
        "Kotak Mahindra Bank Ltd. → KOTAKBANK.NS\"\n",
        ")\n",
        "\n",
        "if st.button(\"Analyze Company\"):\n",
        "    try:\n",
        "        df = fetch_financials_5y(ticker)\n",
        "        ratios = calculate_ratios(df)\n",
        "\n",
        "        st.subheader(\"📌 5-Year Financial Data\")\n",
        "        st.dataframe(df)\n",
        "\n",
        "        st.subheader(\"📈 Financial Ratios (5-Year Trend)\")\n",
        "        st.dataframe(ratios)\n",
        "\n",
        "        st.subheader(\"📊 Ratio Trends\")\n",
        "        st.line_chart(ratios)\n",
        "\n",
        "        verdict, strengths, risks = financial_health_logic(ratios)\n",
        "\n",
        "        st.subheader(\"✅ Financial Health Verdict\")\n",
        "        st.success(verdict)\n",
        "\n",
        "        st.subheader(\"💪 Strengths Identified\")\n",
        "        for s in strengths:\n",
        "            st.write(f\"- {s}\")\n",
        "\n",
        "        if risks:\n",
        "            st.subheader(\"⚠️ Risks Identified\")\n",
        "            for r in risks:\n",
        "                st.write(f\"- {r}\")\n",
        "\n",
        "    except Exception as e:\n",
        "        st.error(f\"Error: {e}\")\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 7,
      "metadata": {
        "id": "qLGIVxN8P4Er",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "a72a9bf1-4738-4466-f7dd-b44d0edd7c28"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting pyngrok\n",
            "  Downloading pyngrok-7.5.0-py3-none-any.whl.metadata (8.1 kB)\n",
            "Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)\n",
            "Downloading pyngrok-7.5.0-py3-none-any.whl (24 kB)\n",
            "Installing collected packages: pyngrok\n",
            "Successfully installed pyngrok-7.5.0\n",
            "Starting Streamlit app in the background...\n",
            "Connecting ngrok...\n",
            "\n",
            "Your Streamlit app is now available at: NgrokTunnel: \"https://33e2ad8b0962.ngrok-free.app\" -> \"http://localhost:8501\"\n",
            "You can also check the Streamlit logs with: !cat streamlit.log\n"
          ]
        }
      ],
      "source": [
        "# Install pyngrok if it's not already installed\n",
        "!pip install pyngrok\n",
        "\n",
        "import time\n",
        "from pyngrok import ngrok\n",
        "\n",
        "# Kill any processes running on port 8501 (Streamlit's default port) to ensure a clean start\n",
        "!kill $(lsof -t -i:8501) 2>/dev/null || true\n",
        "\n",
        "# Start Streamlit in the background\n",
        "# The 'nohup' command allows the process to continue running after the terminal is closed\n",
        "# The '&' symbol sends the process to the background\n",
        "# Output is redirected to 'streamlit.log' to avoid cluttering the cell output\n",
        "print(\"Starting Streamlit app in the background...\")\n",
        "!nohup streamlit run app.py > streamlit.log 2>&1 &\n",
        "\n",
        "# Give Streamlit a moment to start up\n",
        "time.sleep(5)\n",
        "\n",
        "# Ensure the ngrok auth token is set. This token was previously identified in the notebook.\n",
        "ngrok.set_auth_token('330OpEJ5Wz3KPy9vJjAKOzxUX1e_7bSZM1aWqZoWrwQiZCjb1')\n",
        "\n",
        "# Connect ngrok to the Streamlit port (8501)\n",
        "print(\"Connecting ngrok...\")\n",
        "public_url = ngrok.connect(8501)\n",
        "\n",
        "print(f\"\\nYour Streamlit app is now available at: {public_url}\")\n",
        "print(\"You can also check the Streamlit logs with: !cat streamlit.log\")"
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "j4MV3ViR1uG1"
      },
      "execution_count": null,
      "outputs": []
    }
  ],
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}