# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w7-Db65ylnszQ7wSVIocsITF9yh2XARd
"""

import sys
if 'google.colab' in sys.modules:
  !pip install streamlit yfinance

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np

st.set_page_config(page_title="Financial Health Checker", layout="wide")

def safe_get(df, row):
    try:
        return df.loc[row]
    except:
        return None

def fetch_financials_5y(ticker):
    stock = yf.Ticker(ticker)
    income = stock.financials
    balance = stock.balance_sheet

    if income.empty or balance.empty:
        raise ValueError("Financial data not available")

    df = pd.DataFrame({
        "Revenue": safe_get(income, "Total Revenue"),
        "Net Income": safe_get(income, "Net Income"),
        "Operating Income": safe_get(income, "Operating Income"),
        "Current Assets": safe_get(balance, "Current Assets"),
        "Current Liabilities": safe_get(balance, "Current Liabilities"),
        "Inventory": safe_get(balance, "Inventory"),
        "Total Assets": safe_get(balance, "Total Assets"),
        "Total Liabilities": safe_get(balance, "Total Liabilities Net Minority Interest"),
        "Equity": safe_get(balance, "Stockholders Equity"),
    })

    return df.dropna(how="all")

def calculate_ratios(df):
    ratios = pd.DataFrame(index=df.index)

    if "Current Assets" in df and "Current Liabilities" in df:
        ratios["Current Ratio"] = df["Current Assets"] / df["Current Liabilities"]
        ratios["Quick Ratio"] = (
            (df["Current Assets"] - df["Inventory"].fillna(0)) /
            df["Current Liabilities"]
        )

    if "Net Income" in df and "Equity" in df:
        ratios["ROE"] = df["Net Income"] / df["Equity"]

    if "Operating Income" in df and "Revenue" in df:
        ratios["Operating Margin"] = df["Operating Income"] / df["Revenue"]

    if "Total Liabilities" in df and "Total Assets" in df:
        ratios["Debt to Assets"] = df["Total Liabilities"] / df["Total Assets"]

    if "Total Liabilities" in df and "Equity" in df:
        ratios["Debt to Equity"] = df["Total Liabilities"] / df["Equity"]

    return ratios.round(2)

def financial_health_logic(ratios):
    latest = ratios.iloc[0]
    strengths, risks = [], []

    if "Operating Margin" in latest and latest["Operating Margin"] >= 0.2:
        strengths.append("Strong operating profitability")
    elif "Operating Margin" in latest:
        risks.append("Weak operating profitability")

    if "ROE" in latest and latest["ROE"] >= 0.2:
        strengths.append("Efficient capital usage")
    elif "ROE" in latest:
        risks.append("Low return on equity")

    if "Current Ratio" in latest and latest["Current Ratio"] < 1:
        if "Operating Margin" in latest and latest["Operating Margin"] >= 0.15:
            strengths.append("Low liquidity offset by strong cash flows")
        else:
            risks.append("Liquidity pressure")

    if "Debt to Equity" in latest and latest["Debt to Equity"] > 2.5:
        if "ROE" in latest and latest["ROE"] >= 0.15:
            strengths.append("Leverage supported by returns")
        else:
            risks.append("High leverage risk")

    if len(risks) == 0 and len(strengths) >= 3:
        verdict = "🟢 Strong Financial Health"
    elif len(risks) <= 2:
        verdict = "🟡 Moderate Financial Health"
    else:
        verdict = "🔴 Weak Financial Health"

    return verdict, strengths, risks

st.title("📊 Financial Health Checker")

ticker = st.text_input("Enter company ticker (e.g. AAPL, TCS.NS)")

if st.button("Analyze"):
    try:
        df = fetch_financials_5y(ticker)
        ratios = calculate_ratios(df)
        verdict, strengths, risks = financial_health_logic(ratios)

        st.subheader("Financial Data")
        st.dataframe(df)

        st.subheader("Ratios")
        st.dataframe(ratios)

        st.subheader("Verdict")
        st.success(verdict)

        st.subheader("Strengths")
        for s in strengths:
            st.write(f"- {s}")

        if risks:
            st.subheader("Risks")
            for r in risks:
                st.write(f"- {r}")

    except Exception as e:
        st.error(e)

